### PR TITLE
Release 0.3.1 (follows the bots PR)

### PR DESCRIPTION
**Pull request by markotoplak**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by markotoplak** [comment]
@conda-forge-admin, please rerender

**Comment by markotoplak** [comment]
This package seems abandoned (the bot opened a version update PR 3 years ago).

I discovered that there are some issues with the package. Running `pip check` if the package is installed fails. For example, see https://github.com/conda-forge/orange3-feedstock/pull/137

This PR aims to fix this. It updates the version, adds required python versions, and new maintainers. Could @conda-forge/core please merge it? Thanks!

**Comment by ocefpaf** [comment]
@markotoplak we wait for at least 1 week for the maintainers to respond. If they do not, please ping the core group.

**Comment by markotoplak** [comment]
@conda-forge/core could you please now merge this? Basically, it is a new version and it also adds me as a maintainer (see comment above).

**Comment by xhochy** [comment]
@lanzagar needs to approve to be a maintainer as you add him at the same time.

**Comment by lanzagar** [comment]
I approve to be a maintainer and think this can be merged now.

**Pull request merged**
